### ISSUE TITLE
Red Hot Tool Tutorial

### ISSUE THREAD

**Issue by hutt0n** [psiberx/cp2077-red-hot-tools#1]
Hi !
This seems to be THE Number One tool I´ve been looking for quick texture mods preview in-game, 
but after couple of hours trying I´m  desperate/frustrated as there´s no any tutorial what´s needed for this
& how this is actually supposed to work. Thank You in Advance !!! 
Cheers !!!

PS. Psiberx You Rocks !!!

Setup:
Wolvenkit 8.9.0 (stable) 
WolvenKit Editor Red Hot Tools 0.4.6 enabled/installed
WolvenKit Editor CET plugin 1.23.0 enabled/installed
Cyberpunk 2077 (1.61 Jan 2023 v.10366133)  Game CET Plugins installed 

So what is currently happening (or isn´t) actually

Test A)
   1. I´ve modified a texture
   2. Imported the xxx.archive to the XX/pc/hot folder with Wolvenkit by using the Hot Reload button
   3. Started the game (xxx.archive in the hot folder)
   4. In game -> open console -> Hot Reload tools -> Reload Archive (I´ve got a nagging feeling that the auto monitor is doing the 
heavy lifting for me in this case :P)
   5. xxx.archive is removed from the hot folder to the pc/mod folder -> archive is not loaded (in real-time) to the game
   6. No change
   
 Test B)
  1. Started the game (no archives in Hot folder)
  2. Imported the xxx.archive to game as it´s running by using the Hot Reload button in Wolvenkit
  3. In game -> open console -> Hot Reload tools -> Reload Archive (I can´t untick the monitor changes btw)
  5. xxx.archive is removed from the hot folder to the pc/mod folder -> archive is not added/re-loaded (in real-time) to the game
  6. No change
  
  Test C)
  1. Imported the xxx.archive to the XX/pc/hot folder with Wolvenkit by using the Hot Reload button
   2. Started the game (xxx.archive in the hot folder)
   3. In game -> open console -> Hot Reload tools -> Reload Archive 
   4. xxx.archive is removed from the hot folder to the pc/mod folder -> archive is not re-loaded (in real-time) to the game
   5. Made changes to the xxx.archive
   6. Imported the xxx.archive to game in as it´s running by using the Hot Reload button in Wolvenkit
   7. xxx.archive is added to the pc/hot folder but it´s not removed to the pc/mod folder anymore.
   8. No change :(

**Comment by psiberx** [comment]
Hi.
When game is running, just press Hot Reload in WolvenKit. Don't use Hot Reload when game is not running. You don't need console if you use WolvenKit.

For errors check `red4ext/plugins/RedHotTools/RedHotTools.log`. If file is stuck in `hot` dir, then something is broken.

It's heavely depends on what exactly are you changing. Some changes can be seen instantly, some change require game object to respawn, some changes may require exit to main menu to reload the world, etc.
